<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Issuer Name
    |--------------------------------------------------------------------------
    | Shown in authenticator apps (e.g. Google Authenticator) next to the
    | account entry. Defaults to your app name when null.
    |--------------------------------------------------------------------------
    */

    'issuer' => env('MFA_ISSUER', 'MyApp'),

    /*
    |--------------------------------------------------------------------------
    | TOTP Settings
    |--------------------------------------------------------------------------
    | These settings control the time-based one-time passwords generated by the
    | package. The default settings are suitable for most applications.
    | If you need to customize them, you may do so here.
    | digits: The number of digits in the generated code (default: 6).
    | period: The time step in seconds for code generation (default: 30).
    | window: The number of time steps to check for code validity (default: 1).
    | algorithm: The hashing algorithm to use (default: 'sha1').
    */

    'totp' => [
        'digits'    => 6,
        'period'    => 30,
        'window'    => 1,
        'algorithm' => 'sha1',
    ],

];
